from termcolor import colored, cprint
cprint(" " * 18, end="")
cprint(" ", "white", "on_yellow", end=" ")
cprint(" ", "white", "on_white", end=" ")
cprint(" ", "white", "on_red")
cprint(" " * 16, end="")
cprint(" " * 9, "white", "on_blue")
cprint(" " * 13, end="")
cprint("~" * 15, "red", "on_light_grey")
cprint(" " * 13, end="")
cprint(" " * 15, "white", "on_light_green")
cprint(" " * 8, end="")
cprint("=" * 24, "white", "on_light_blue")
print(" " * 13 + colored("Selamat ulang tahun", "blue"))
